# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 06:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('slug', models.CharField(db_index=True, max_length=100, verbose_name='Website')),
                ('content', models.TextField(blank=True, default='')),
                ('published', models.BooleanField(default=True, verbose_name='Published ')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author')),
            ],
            options={
                'verbose_name': 'Course',
            },
        ),
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Column Name')),
                ('slug', models.CharField(max_length=256, verbose_name='Column wwww')),
                ('intro', models.TextField(default='', verbose_name='Column Introduction')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name_plural': 'Column',
                'verbose_name': 'Column',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='column',
            field=models.ManyToManyField(to='news.Column', verbose_name="Column's Article"),
        ),
    ]
