# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 08:25
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20171128_0731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=DjangoUeditor.models.UEditorField(blank=True, default='', verbose_name='content'),
        ),
    ]
